mkdir model01
cd model01
mkdir INPUT
mkdir OUTPUT
mkdir RESULTS
mkdir RUNDIR
mkdir AUX
cd OUTPUT/
mkdir INTEXT
mkdir EXTERNAL
cd ..
cd RESULTS/
mkdir SUBSPEC
cd /Users/cbourque/astrophysics/star-formation/SIMULATIONS
mkdir model02
cd model02
mkdir INPUT
mkdir OUTPUT
mkdir RESULTS
mkdir RUNDIR
mkdir AUX
cd OUTPUT/
mkdir INTEXT
mkdir EXTERNAL
cd ..
cd RESULTS/
mkdir SUBSPEC
cd /Users/cbourque/astrophysics/star-formation/SIMULATIONS
mkdir model03
cd model03
mkdir INPUT
mkdir OUTPUT
mkdir RESULTS
mkdir RUNDIR
mkdir AUX
cd OUTPUT/
mkdir INTEXT
mkdir EXTERNAL
cd ..
cd RESULTS/
mkdir SUBSPEC
cd /Users/cbourque/astrophysics/star-formation/SIMULATIONS
mkdir model04
cd model04
mkdir INPUT
mkdir OUTPUT
mkdir RESULTS
mkdir RUNDIR
mkdir AUX
cd OUTPUT/
mkdir INTEXT
mkdir EXTERNAL
cd ..
cd RESULTS/
mkdir SUBSPEC
cd /Users/cbourque/astrophysics/star-formation/SIMULATIONS
mkdir model05
cd model05
mkdir INPUT
mkdir OUTPUT
mkdir RESULTS
mkdir RUNDIR
mkdir AUX
cd OUTPUT/
mkdir INTEXT
mkdir EXTERNAL
cd ..
cd RESULTS/
mkdir SUBSPEC
cd /Users/cbourque/astrophysics/star-formation/SIMULATIONS
mkdir model06
cd model06
mkdir INPUT
mkdir OUTPUT
mkdir RESULTS
mkdir RUNDIR
mkdir AUX
cd OUTPUT/
mkdir INTEXT
mkdir EXTERNAL
cd ..
cd RESULTS/
mkdir SUBSPEC
cd /Users/cbourque/astrophysics/star-formation/SIMULATIONS
mkdir model07
cd model07
mkdir INPUT
mkdir OUTPUT
mkdir RESULTS
mkdir RUNDIR
mkdir AUX
cd OUTPUT/
mkdir INTEXT
mkdir EXTERNAL
cd ..
cd RESULTS/
mkdir SUBSPEC
cd /Users/cbourque/astrophysics/star-formation/SIMULATIONS
mkdir model08
cd model08
mkdir INPUT
mkdir OUTPUT
mkdir RESULTS
mkdir RUNDIR
mkdir AUX
cd OUTPUT/
mkdir INTEXT
mkdir EXTERNAL
cd ..
cd RESULTS/
mkdir SUBSPEC
cd /Users/cbourque/astrophysics/star-formation/SIMULATIONS
mkdir model09
cd model09
mkdir INPUT
mkdir OUTPUT
mkdir RESULTS
mkdir RUNDIR
mkdir AUX
cd OUTPUT/
mkdir INTEXT
mkdir EXTERNAL
cd ..
cd RESULTS/
mkdir SUBSPEC
cd /Users/cbourque/astrophysics/star-formation/SIMULATIONS
mkdir model10
cd model10
mkdir INPUT
mkdir OUTPUT
mkdir RESULTS
mkdir RUNDIR
mkdir AUX
cd OUTPUT/
mkdir INTEXT
mkdir EXTERNAL
cd ..
cd RESULTS/
mkdir SUBSPEC
cd /Users/cbourque/astrophysics/star-formation/SIMULATIONS
mkdir model11
cd model11
mkdir INPUT
mkdir OUTPUT
mkdir RESULTS
mkdir RUNDIR
mkdir AUX
cd OUTPUT/
mkdir INTEXT
mkdir EXTERNAL
cd ..
cd RESULTS/
mkdir SUBSPEC
cd /Users/cbourque/astrophysics/star-formation/SIMULATIONS
mkdir model12
cd model12
mkdir INPUT
mkdir OUTPUT
mkdir RESULTS
mkdir RUNDIR
mkdir AUX
cd OUTPUT/
mkdir INTEXT
mkdir EXTERNAL
cd ..
cd RESULTS/
mkdir SUBSPEC
cd /Users/cbourque/astrophysics/star-formation/SIMULATIONS
mkdir model13
cd model13
mkdir INPUT
mkdir OUTPUT
mkdir RESULTS
mkdir RUNDIR
mkdir AUX
cd OUTPUT/
mkdir INTEXT
mkdir EXTERNAL
cd ..
cd RESULTS/
mkdir SUBSPEC
cd /Users/cbourque/astrophysics/star-formation/SIMULATIONS
mkdir model14
cd model14
mkdir INPUT
mkdir OUTPUT
mkdir RESULTS
mkdir RUNDIR
mkdir AUX
cd OUTPUT/
mkdir INTEXT
mkdir EXTERNAL
cd ..
cd RESULTS/
mkdir SUBSPEC
cd /Users/cbourque/astrophysics/star-formation/SIMULATIONS
mkdir model15
cd model15
mkdir INPUT
mkdir OUTPUT
mkdir RESULTS
mkdir RUNDIR
mkdir AUX
cd OUTPUT/
mkdir INTEXT
mkdir EXTERNAL
cd ..
cd RESULTS/
mkdir SUBSPEC
cd /Users/cbourque/astrophysics/star-formation/SIMULATIONS
mkdir model16
cd model16
mkdir INPUT
mkdir OUTPUT
mkdir RESULTS
mkdir RUNDIR
mkdir AUX
cd OUTPUT/
mkdir INTEXT
mkdir EXTERNAL
cd ..
cd RESULTS/
mkdir SUBSPEC
cd /Users/cbourque/astrophysics/star-formation/SIMULATIONS
mkdir model17
cd model17
mkdir INPUT
mkdir OUTPUT
mkdir RESULTS
mkdir RUNDIR
mkdir AUX
cd OUTPUT/
mkdir INTEXT
mkdir EXTERNAL
cd ..
cd RESULTS/
mkdir SUBSPEC
cd /Users/cbourque/astrophysics/star-formation/SIMULATIONS
mkdir model18
cd model18
mkdir INPUT
mkdir OUTPUT
mkdir RESULTS
mkdir RUNDIR
mkdir AUX
cd OUTPUT/
mkdir INTEXT
mkdir EXTERNAL
cd ..
cd RESULTS/
mkdir SUBSPEC
cd /Users/cbourque/astrophysics/star-formation/SIMULATIONS
mkdir model19
cd model19
mkdir INPUT
mkdir OUTPUT
mkdir RESULTS
mkdir RUNDIR
mkdir AUX
cd OUTPUT/
mkdir INTEXT
mkdir EXTERNAL
cd ..
cd RESULTS/
mkdir SUBSPEC
cd /Users/cbourque/astrophysics/star-formation/SIMULATIONS
mkdir model20
cd model20
mkdir INPUT
mkdir OUTPUT
mkdir RESULTS
mkdir RUNDIR
mkdir AUX
cd OUTPUT/
mkdir INTEXT
mkdir EXTERNAL
cd ..
cd RESULTS/
mkdir SUBSPEC
cd /Users/cbourque/astrophysics/star-formation/SIMULATIONS
mkdir model21
cd model21
mkdir INPUT
mkdir OUTPUT
mkdir RESULTS
mkdir RUNDIR
mkdir AUX
cd OUTPUT/
mkdir INTEXT
mkdir EXTERNAL
cd ..
cd RESULTS/
mkdir SUBSPEC
cd /Users/cbourque/astrophysics/star-formation/SIMULATIONS
mkdir model22
cd model22
mkdir INPUT
mkdir OUTPUT
mkdir RESULTS
mkdir RUNDIR
mkdir AUX
cd OUTPUT/
mkdir INTEXT
mkdir EXTERNAL
cd ..
cd RESULTS/
mkdir SUBSPEC
cd /Users/cbourque/astrophysics/star-formation/SIMULATIONS
mkdir model23
cd model23
mkdir INPUT
mkdir OUTPUT
mkdir RESULTS
mkdir RUNDIR
mkdir AUX
cd OUTPUT/
mkdir INTEXT
mkdir EXTERNAL
cd ..
cd RESULTS/
mkdir SUBSPEC
cd /Users/cbourque/astrophysics/star-formation/SIMULATIONS
